### ISSUE TITLE
broken links in README, pha_pretrained_model missing

### ISSUE THREAD

**Issue by gpetho** [Celestial-Bai/INHERIT#1]
It is impossible to run INHERIT according to the instructions in the readme because the phage pre-trained model seems to be unavailable. In the readme this link: [Phage pre-trained model download link](https://drive.google.com/file/d/169BaPS4BjK-cmnfabpyjNVTjFtyzhbyC/view?usp=sharing) in fact points to `INHERIT.pt`, which is the combined model's `state_dict`, if I am not mistaken. So I believe it is actually the link further down the page, which reads [Fine-tuned INHERIT download link](https://drive.google.com/file/d/1uGFZWKoonVMjFHD4bRmutoFMVZRMX6UG/view?usp=sharing) , that should point to this `INHERIT.pt` file. This latter link seems to be dead. I could not find any URL in the repository that points to the actual location of the `pha_pretrained_model` directory.

**Comment by yaozhong** [comment]
HI, Bai-kun

Please response this inquiry in the Github.

Best,

Zhang

**Comment by Celestial-Bai** [comment]
Hi @gpetho
Sorry for brining you inconvenience. We have corrected the link so you can download the pre-trained models normally.

**Comment by gpetho** [comment]
Thank you very much, I was able to download the phage model with the corrected link.
