### ISSUE TITLE
Installation of dependencies failed

### ISSUE THREAD

**Issue by leannmlindsey** [Celestial-Bai/INHERIT#3]
Hello, I have tried to install your software on my mac and also on a Linux cluster and both times the installation of dependencies failed.  I am now trying to install all dependencies by hand but this is taking a very long time (do you really need so many python packages?  some seem unnecessary...)

on Mac the install fails with this message:
Collecting fugashi>=1.0
  Using cached fugashi-1.2.1.tar.gz (337 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/qx/8lslztxj78vb1k3wfmjncjbc0000gn/T/pip-install-5bhsw1vf/fugashi_9da29432e7a544858ccea6458f7c2737/setup.py", line 15, in <module>
          output, data_files = check_libmecab()
        File "/private/var/folders/qx/8lslztxj78vb1k3wfmjncjbc0000gn/T/pip-install-5bhsw1vf/fugashi_9da29432e7a544858ccea6458f7c2737/fugashi_util.py", line 58, in check_libmecab
          raise RuntimeError("Could not configure working env. Have you installed MeCab?")
      RuntimeError: Could not configure working env. Have you installed MeCab?
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

on LINUX the install fails with this message:
Collecting sagemaker>=2.31.0
  Downloading sagemaker-2.129.0.tar.gz (660 kB)
     |████████████████████████████████| 660 kB 3.9 MB/s 
Collecting scikit-learn==0.24.1
  Using cached scikit_learn-0.24.1-cp39-cp39-manylinux2010_x86_64.whl (23.8 MB)
Collecting sentencepiece==0.1.91
  Using cached sentencepiece-0.1.91.tar.gz (500 kB)
    ERROR: Command errored out with exit status 1:
     command: /uufs/chpc.utah.edu/sys/installdir/rosetta/3.13/miniconda3/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-fkkltm_m/sentencepiece_57b58b55541749d294c948dd627060da/setup.py'"'"'; __file__='"'"'/tmp/pip-install-fkkltm_m/sentencepiece_57b58b55541749d294c948dd627060da/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-e4hr4gr3
         cwd: /tmp/pip-install-fkkltm_m/sentencepiece_57b58b55541749d294c948dd627060da/
    Complete output (5 lines):
    Package sentencepiece was not found in the pkg-config search path.
    Perhaps you should add the directory containing `sentencepiece.pc'
    to the PKG_CONFIG_PATH environment variable
    Package 'sentencepiece', required by 'virtual:world', not found
    Failed to find sentencepiece pkgconfig
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/ba/f6/520b56e5977f62aee48833da8b4ff2fdc2b10ebfa0dd78556b1d707d4086/sentencepiece-0.1.91.tar.gz#sha256=f9700cf607ea064d9fad34c751fbf49953dcc56fe68c54b277481aa0aec5c18f (from https://pypi.org/simple/sentencepiece/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement sentencepiece==0.1.91 (from versions: 0.0.0, 0.0.2, 0.0.3, 0.0.4, 0.0.5, 0.0.6, 0.0.7, 0.0.9, 0.1.0, 0.1.1, 0.1.2, 0.1.3, 0.1.83, 0.1.86, 0.1.91, 0.1.92, 0.1.94, 0.1.95, 0.1.96, 0.1.97)
ERROR: No matching distribution found for sentencepiece==0.1.91

**Comment by Celestial-Bai** [comment]
Hi leannmlindsey,

Unfortunately, we didn't find this issue during our installation. But I think this may be cause by the Transformers. I will update a version that directly use Transformers as a library in the future. This will make us use INHERIT, even DNABERT more convenient. We don't have to install some unnecessary packages in that way.
My suggestion is you can try to install DNABERT first and then INHERIT to see if that solves the problem. Because there is a version difference between the transformers used by INHERIT and DNABERT, you may need to upgrade some of the packages afterwards, but it may solve your problem.
