### ISSUE TITLE
Where is test.fasta?

### ISSUE THREAD

**Issue by hhy-joseph** [Celestial-Bai/INHERIT#4]
As title.

I'm trying to run python3 IHT_predict.py --sequence test.fasta --withpretrain True --model INHERIT.pt --out test_out.txt

**Comment by Celestial-Bai** [comment]
Hi hhy-joseph,

Sorry for making you confused.
Here I submit a sample file of test.fasta, named as test_phage.fasta. I also put an output file on the GitHub page.
I think you can get similar output with your device.

**Comment by hhy-joseph** [comment]
Hi, 

Thanks! Do you have bacteria sequence examples as well?
