### ISSUE TITLE
Request for Access to Phage Data if possible

### ISSUE THREAD

**Issue by hhy-joseph** [Celestial-Bai/INHERIT#6]
I recently came across your paper titled "Identification of Bacteriophage Genome Sequences with Representation Learning" and was fascinated by your work in utilizing representation learning for phage genome identification. I am currently working on a project involving pre-training DNABERT, and I believe that your phage data would greatly benefit our research.

I read in your paper that you searched for the keyword 'phage' on NCBI, downloaded all sequences longer than 500 bp, and manually checked each of them. I understand the effort you put into this data collection process, and I would like to inquire if it would be possible for you to share the phage data with me. It would be immensely helpful if you could provide the data in a compressed format, such as a ZIP file.

By replicating some of the steps described in your paper, we aim to pre-train DNABERT using a similar dataset to assess its performance and further contribute to the advancement of phage genome analysis. Having access to your phage data would not only expedite our research but also allow us to compare our findings with yours, providing valuable insights into the robustness of the DNABERT model.

I understand that sharing data might involve certain considerations, such as data privacy and intellectual property rights. If you have any concerns regarding data sharing, I assure you that we will strictly adhere to your requirements and guidelines. We are committed to using the data solely for research purposes and will uphold any restrictions you deem necessary.

If it is possible for you to share the phage data, could you please let me know the process or any requirements for obtaining the dataset? I would greatly appreciate your assistance in this matter.

Thank you very much for your time and consideration. I look forward to your response and the possibility of collaborating on this research endeavor.

**Comment by Celestial-Bai** [comment]
Hi hhy-joseph,

Glad to see your comment.
Our data information is public in our supplementary materials. Feel free download them via the accessions.
You have the flexibility to add or remove these phage samples to build your own dataset.
